DB_USER = "postgres"
DB_PASS = "your_password"
DB_HOST = "your_host"
DB_ADMIN_URL = f"postgresql+psycopg2://{DB_USER}:{DB_PASS}@{DB_HOST}/admin"
DB_ARRIS_URL = f"postgresql+psycopg2://{DB_USER}:{DB_PASS}@{DB_HOST}/arris"
